apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: lidfem-app
  name: lidfem-app
  namespace: data-science
  resourceVersion: "440723924"
  uid: 3ac87e4f-b8fe-4472-a5c9-242728bc8e09
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: lidfem-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lidfem-app
    spec:
      containers:
      - image: 941961614774.dkr.ecr.us-west-2.amazonaws.com/lidfem-app:latest
        imagePullPolicy: IfNotPresent
        name: lidfemapp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
